#!/usr/bin/env node

var program = require('commander');

program
  .version('0.0.1')
  .option('-g, --greet [name]', 'greets a person of the specified name.')
  .option('-a, --awesome', 'prints AWESOME!!!!')
  .parse(process.argv);

if (program.greet) console.log('Hello there %s!', program.greet);
if (program.awesome) console.log('AWESOME!!!!');
